import { createElement } from 'lwc';
import My2ndCallingFuctionToOtherEvent from 'c/my2ndCallingFuctionToOtherEvent';

describe('c-my2-nd-calling-fuction-to-other-event', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-my2-nd-calling-fuction-to-other-event', {
            is: My2ndCallingFuctionToOtherEvent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});